// Mocks generated by Mockito 5.4.4 from annotations
// in todo_list/test/unit_test/features/map/domain/use_cases/get_todo_list_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_list/features/todo/data/models/todo_item_model.dart'
    as _i5;
import 'package:todo_list/features/todo/domain/repositories/todo_repository.dart'
    as _i2;
import 'package:todo_list/features/todo/domain/use_cases/get_todo_list_usecase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTodoRepository_0 extends _i1.SmartFake
    implements _i2.TodoRepository {
  _FakeTodoRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTodoListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTodoListUseCase extends _i1.Mock
    implements _i3.GetTodoListUseCase {
  MockGetTodoListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TodoRepository get todoRepository => (super.noSuchMethod(
        Invocation.getter(#todoRepository),
        returnValue: _FakeTodoRepository_0(
          this,
          Invocation.getter(#todoRepository),
        ),
      ) as _i2.TodoRepository);

  @override
  _i4.Future<List<_i5.TodoItemModel>> call(dynamic params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<List<_i5.TodoItemModel>>.value(<_i5.TodoItemModel>[]),
      ) as _i4.Future<List<_i5.TodoItemModel>>);
}
