name: todo_list
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  intl: ^0.18.0
  flutter_localization: ^0.2.0
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  freezed: ^2.4.6
  flutter_dotenv: ^5.1.0
  dio: ^5.4.0
  get_it: ^7.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.8
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  freezed_annotation: ^2.4.1


flutter:
  generate: true
  uses-material-design: true

  assets:
    - production.env
